[installed]
client_id = "191921890644-sbgvqs3umf4ult960q6qvell96ssqn1r.apps.googleusercontent.com"
client_secret = "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"
redirect_uris = ["https://app-search-console-extractor.streamlit.app/"]