[installed]
client_id = "191921890644-fm7o55ra56ciiimv4nt0a4k632btdkd3.apps.googleusercontent.com"
client_secret = "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"
redirect_uris = ["https://app-search-console-extractor.streamlit.app"]
