[installed]
client_id = "191921890644-trlvv3hpanbcu8d7uhf5bqak6r89g1tg.apps.googleusercontent.com "
client_secret = "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"
redirect_uris = "https://app-search-console-extractor.streamlit.app/"
